version: "3"
services:
  mysql:
    image: "mysql"
    container_name: "mysql_db"
    ports:
      - "3306:3306"
    volumes:
      - "/home/skmitra/Coding/otp-service/db:/var/lib/mysql"
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_USER=user"
      - "MYSQL_PASSWORD=password"
      - "MYSQL_DATABASE=otp_service"
